#!/usr/bin/env bash
set -euo pipefail
source "$(cd "$(dirname "$0")" && pwd)/env.sh"

pixdr_require_cmd python3 >/dev/null

ASSET_DIR="${PIXDR_APP_DIR}/assets"
TMP_DIR="${PIXDR_BUILD_DIR}/uhd-images"
DOWNLOADER="${PIXDR_PREFIX}/lib/uhd/utils/uhd_images_downloader.py"

if [[ ! -f "${DOWNLOADER}" ]]; then
  echo "ERROR: UHD image downloader not found: ${DOWNLOADER}" >&2
  echo "Run scripts/build-native.sh first, or set PIXDR_PREFIX to a UHD Android prefix." >&2
  exit 1
fi

mkdir -p "${ASSET_DIR}" "${TMP_DIR}"

python3 "${DOWNLOADER}" \
  --types "b2.*" \
  --install-location "${TMP_DIR}"

for f in usrp_b200_fw.hex usrp_b200_fpga.bin usrp_b210_fpga.bin; do
  if [[ -f "${TMP_DIR}/${f}" ]]; then
    cp "${TMP_DIR}/${f}" "${ASSET_DIR}/${f}"
  else
    found="$(find "${TMP_DIR}" -name "${f}" -print -quit)"
    [[ -n "${found}" ]] || { echo "ERROR: missing image after download: ${f}" >&2; exit 1; }
    cp "${found}" "${ASSET_DIR}/${f}"
  fi
done

cat > "${ASSET_DIR}/README.md" <<'EOF'
# Runtime UHD images

This directory is generated by `scripts/fetch-uhd-images.sh`.
Only these B200/B210 files are packaged into the APK:

- `usrp_b200_fw.hex`
- `usrp_b200_fpga.bin`
- `usrp_b210_fpga.bin`

The binary image files are ignored by git. Check Ettus/UHD licensing before
redistributing them as repository contents or release assets.
EOF

ls -lh \
  "${ASSET_DIR}/usrp_b200_fw.hex" \
  "${ASSET_DIR}/usrp_b200_fpga.bin" \
  "${ASSET_DIR}/usrp_b210_fpga.bin"
